document.write('<!--PC导航栏-->')
document.write('<nav class="nav-bar-holder" style="background-color:#303643">')
document.write('    <!--<img src="https://i.postimg.cc/RFyJLX7P/headimg.jpg" alt="Head Image" style="text-align: left;width:auto">-->')
document.write('    <div class="nav-bar" id="nav-bar">')
document.write('        <div class="logo-box">')
document.write('            <a href="index.html" class="blog-title ta-c"><img style="vertical-align: top;height:32px" alt="logo"src="https://i.328888.xyz/2023/04/16/iE7BTH.png" /></a>')
document.write('        </div>')
//https://i.328888.xyz/2023/04/16/iE7pEF

document.write('        <div class="nb-a-holder" id="home"><a class="nb-a ta-c" href="../templates/index.html">首页</a></div>')
document.write('        <div class="nb-a-holder" id="home"><a class="nb-a ta-c" href="../templates/aulim.html">关于</a></div>')
document.write('        <div class="nb-a-holder" id="home"><a class="nb-a ta-c" href="../templates/web.sign.html">公告</a></div>')
document.write('        <div class="nb-a-holder"><a class="nb-a ta-c" href="../templates/category.html">文章分类</a></div>')
document.write('        <div class="nb-a-holder"><a class="nb-a ta-c" href="../templates/archive.html">文件归档</a></div>')
document.write('        <div class="nb-a-holder"><a class="nb-a ta-c" href="../templates/issue.html">讨论</a></div>')
document.write('        <div class="nb-a-holder"><a class="nb-a ta-c" href="../templates/propagate.html">宣传墙</a></div>')
document.write('        <div class="nb-a-holder"><a class="nb-a ta-c" href="../templates/link.html">友情链接</a></div>')
document.write('    </div><br>')
// document.write('    <div id="nav-bar-cover" style="width:100%;height:30px"></div>')
document.write('</nav>')
document.write('<!--mobile导航栏-->')
document.write('<nav class="mobile-nav">')
document.write('    <img src="https://i.postimg.cc/RFyJLX7P/headimg.jpg" alt="Head Image" style="text-align: left;width:100%">')
document.write('    <div class="logo-box">')
document.write('        <a href="index.html" class="blog-title ta-c">')
document.write('            <img style="vertical-align: top;" alt="logo" src="../img/user.jpeg">')
document.write('        </a>')
document.write('    </div>')
document.write('    <a id="mobile_cate" alt="null" href="javascript:void(0);"><img style="width:35px" alt="moblie-nav" src="../img/cate.jpeg"></a>')
document.write('</nav>')
document.write('<ul id="nav-m-list">')
document.write('    <li id="cancel-li"><a class="fr" id="cancel" href="javascript:void(0);"></a></li>')
document.write('    <li id="m-img-li">')
document.write('        <img id="m-img" alt="雄关漫道真如铁，而今迈步从头越" src="../img/user.jpeg">')
document.write('    </li>')
document.write('    <li><a class="w-h-100 fl" href="../templates/index.html">首页</a></li>')
document.write('    <li><a class="w-h-100 fl" href="../templates/aulim.html">关于</a></li>')
document.write('    <li><a class="w-h-100 fl" href="../templates/web.sign.html.html">公告板</a></li>')
document.write('    <li><a class="w-h-100 fl" href="../templates/category.html">文章分类</a></li>')
document.write('    <li><a class="w-h-100 fl" href="../templates/archive.html">文件归档</a></li>')
document.write('    <li><a class="w-h-100 fl" href="../templates/issue.html">讨论</a></div>')
document.write('    <li><a class="w-h-100 fl" href="../templates/propagate.html">宣传墙</a></div>')
document.write('    <li><a class="w-h-100 fl" href="../templates/link.html">友情链接</a></li>')
document.write('</ul>')