function print_page(page){
    // 鄂市-2022.12.17
    if(page==0){//手机版导航页
        document.write('    <div class="column-container">')
        document.write('    <ul class="column_box" id="like-box">')
        document.write('        <li class="column-title">')
        document.write('        <span class="at-sort b-b-ece fl"><a class="at-sort-comment-a c-666 fl">社团-导航</a></span>')
        document.write('    </li>')
        document.write('    <li class="column-category">')
        document.write('        <a href="about.html?name=1">赤原社</a>')
        document.write('    </li>')
        document.write('    <li class="column-category">')
        document.write('        <a href="about.html?name=2">兰州红松学会-目前处于不活跃状态</a>')
        document.write('    </li>')
        document.write('    <li class="column-category">')
        document.write('        <a href="about.html?name=3">呼马学会</a>')
        document.write('    </li>')
        document.write('    <li class="column-category">')
        document.write('        <a href="about.html?name=4">北桥联社</a>')
        document.write('    </li>')
        document.write('    <li class="column-category">')
        document.write('        <a href="about.html?name=5">马列社-为公社</a>')
        document.write('    </li>')
        document.write('    <li class="column-category">')
        document.write('        <a href="about.html?name=6">鄂尔多斯-目前处于待发展状态</a>')
        document.write('    </li>')
        document.write('    <li class="column-category">')
        document.write('        <a href="about.html?name=7">新赤峰学社-目前处于待发展状态</a>')
        document.write('    </li>')
        document.write('</ul>')
        document.write('</div>')
    }
    if(page==1){
        document.write('    <ul class="link-box">')
        document.write('    <br>')
        document.write('    <li class="person-img-li" style="text-align: center;">')
        document.write('        <img src="../img/club/1.jpg" alt="RPC" id="person-img" style="width: 37%;">')
        document.write('    </li>')
        document.write('    <li>')
        document.write('        <h3 style="text-align: center;">包头九中赤原青年马克思主义社</h3>')
        document.write('        <h5 style="text-align: center;">The Youth Marxism Club of No.9 Senior High,Baotou</h5>')
        document.write('        <h5 style="text-align: right;"> <a href="./about.html?name=1.1">English ver</a></h5>')
        document.write('        <span class="description" style="width: 100%;">')
        document.write('        <h3>社长：</h3>QQ：1038171180<br>')
        document.write('        <h3>成立日期：2021.5.29</h3>')
        document.write('        <h3>简介：</h3>')
        document.write('          这里是@包头九中赤原青年马克思主义社（简称赤原社）, 赤原社是将培养青年进步学生知识分子为坚定社会主义和共产主义者作为核心工作任务的学生自学组织。 作为一个青年学生的进步组织，本社在本着“以<strong>马克思列宁主义毛泽东思想</strong>为指导，积极开展马克思主义理论的宣传与实践活动，培养并造就用马克思主义中国化最新成果武装的青年马克思主义者和建设共产主义事业的可靠接班人。”的宗旨下，着力于从赢得青年、赢得未来的高度，通过开展对马克思主义理论深入的学习，帮助同学们用所学理论知识解决在理论学习、生活实践中所遇到的难点和疑点问题，不断深化对马克思列宁主义毛泽东思想的认识，使中学生骨干、团干部、青年知识分子等青年群体的思政素质、理论水平、创新能力、实践能力和组织协调能力不断提高，从而进一步坚定社会主义道路的信念，成长为社会主义事业的合格建设者和接班人。<br>')
        document.write('        <h3>意识形态：</h3>包括但不限于：马克思主义，苏联马克思主义理论，西方马克思主义哲学理论，青年黑格尔派，无政府共产主义。我们主张在容忍意识形态差异内，以团结大多数支持共产主义事业的青年学生为基础，以和谐互助，和平共处为方针，开展共产主义理论和实践教学。')
        document.write('        <h3>活动时间：</h3>（除考试周外）每周一周四下午5.05-5.50<br>')
        document.write('        <h3>活动地点：</h3>社团活动中心<br>')
        document.write('        <br><h3>联系方式:</h3><br>')
        document.write('    </span>')
        document.write('    <div class="qrcode-container">')
        document.write('        <div class="sub-container">')
        document.write('            <img class="link-img" src="../img/MCStudy.jpeg" alt="赤原社马克思主义学习群">')
        document.write('            <p>赤原社马克思主义学习群</p>')
        document.write('        </div>')
        document.write('        <div class="sub-container">')
        document.write('            <img class="link-img" src="../img/MCOnline.jpeg" alt="赤原社线上群">')
        document.write('            <p>赤原社线上群</p>')
        document.write('        </div>')
        document.write('    </div>')
        document.write('    <br>')
        document.write('    <p style="text-align:center ;"><strong>  一个幽灵，一个共产主义的幽灵在欧洲上空飘荡<br> Ein Gespenst geht um in Europa-das Gespenst des Kommunismus. </strong></p>')
        document.write('    <h6 style="text-align: right;">——Karl Marx</h6>')
        document.write('    <p style="text-align:center ;"><strong>一切反动派都是纸老虎</strong><h6 style="text-align: right;">——毛泽东</h6></p>')
        document.write('    <p style="text-align:center ;"><strong>苏联已经证明了，没有资本家，工人会生活的很好，可资本家还没有向我们证实资本家可以离开无产者而生存。</strong><h6 style="text-align: right;">——恩斯特 台尔曼</h6></p>')
        document.write('</li>')
        document.write('</ul>')
    }
    if(page==1.1){
        document.write('<ul class="link-box">')
        document.write('<br>')
        document.write('<li class="person-img-li" style="text-align: center;">')
        document.write('<img src="../img/club/1.jpg" alt="RPC" id="person-img" style="width: 37%;">')
        document.write('</li>')
        document.write('<li>')
        document.write('<h5 style="text-align: center;">The Youth Marxism Club of No.9 Senior High,Baotou</h5>')
        document.write('<h3 style="text-align: center;">包头九中赤原青年马克思主义社</h3>')
        document.write('<h5 style="text-align: right;"> <a href="./about.html?name=1">中文版</a></h5>')
        document.write('<span class="description" style="width: 100%;">')
        document.write('<h3>Monitor:</h3>QQ：1038171180<br>')
        document.write('<h3>Establishment Date:2021.5.29</h3><br>')
        document.write('<h3>Introduction:</h3>')
        document.write("  Here's Youth Marxism Club of No.9 Senior High,Baotou（also Red Plain Club,RPC,a student-runned organization which has the task to cultivate the students' sense of identity to socialism and communism.While with progressism,we're guided by Marxist-Leninist Maoism,and are willing to carry out activities with the theme of theories and practice.<br>")
        document.write('<h3>Ideologies:</h3>')
        document.write('  Including but not limited to: Orthdox Marxists, Leninist-Stalinists, Western Marxists, Youth Hegelists，Anarcho-Communist。We advocate that we should carry out the teaching of communist theory and practice on the basis of uniting the majority of young students who support the cause of communism within tolerance of ideological differences while to take harmony, mutual assistance and peaceful coexistence as the policy.')
        document.write('<h3>Time:</h3>  (Except for the Exam Week)5.05-5.50pm,MON & THUR<br>')
        document.write('<h3>Position:</h3>')
        document.write('  Center of Club Activities')
        document.write('<br><h3>Contact:</h3><br>')
        document.write('</span>')
        document.write('<img class="link-img" src="../img/MCStudy.jpeg" alt="RPC Study Group"><img class="link-img" src="../img/MCOnline.jpeg" alt="RPCOnline">')
        document.write('<h6>   RPC Study Group              RPCOnline</h6>')
        document.write('<br>')
        document.write('<p style="text-align:center ;"><strong> A ghost, a ghost of communism is floating over Europe<br> Ein Gespenst geht um in Europa-das Gespenst des Kommunismus. </strong></p>')
        document.write('<h6 style="text-align: right;">——Karl Marx</h6>')
        document.write('<p style="text-align:center ;"><strong>All the reactionaries are the Papertiger</strong><h6 style="text-align: right;">——Mao Tsetung</h6></p>')
        document.write("<p style='text-align:center ;'><strong>The Soviet Union has confirmed:the working class lives well without the bourgeoisie, but the bourgeoisie hasn't proved that they can live well without the workers on the contrary。</strong><h6 style='text-align: right;'>——Ernst Thälmann</h6></p>")
        document.write('</li>')
        document.write(' </ul>')
    }
    if(page==2){
        // document.write('<ul class="link-box">')
        // document.write('<br>')
        // document.write('<li class="person-img-li" style="text-align: center;">')
        // document.write('<img src="../img/club/3.jpg" alt="Hongsong Xuehui" id="person-img" style="width: 37%;">')
        // document.write('</li>')
        // document.write('<li>')
        // document.write('        <h3 style="text-align: center;">兰州红松学会</h3>')
        // document.write('        <h5 style="text-align: center;">Hongsong Xuehui, Lanzhou,Gansu Prov.</h5>')
        // document.write('        <span class="description" style="width: 100%;">')
        // document.write('            <h3>学会会长：</h3>浮生<br>')
        // // document.write('            <h3>成立日期：</h3>')
        // document.write('            <h3>介绍</h3>')
        // document.write('              中国红松学会是以马克思列宁主义、毛泽东思想为指导纲领的学生进步组织，本学会旨在联合众多进步组织，将新的思想传播给广大青年朋友们。中国红松学会坚定地走马克思列宁-毛泽东道路，永远坚定不移地和广大工人朋友站在一边，不忘阶级斗争，不忘革命思想，不忘教员教诲，坚决反对中国修正主义共产党及一切修正主义势力，反对一切狭隘的民族主义，反对一切极端过激主义。<br>')
        // document.write('            <h3>学会口号会歌及历代会长寄语</h3>')
        // document.write('              学会口号：胜利属于人民，全世界的无产者，我们联合！<br>')
        // document.write('              学会会歌：《国际歌》<br>')
        // document.write('              第一任会长寄语：内不愧心，外不媚俗，艰心苦修，自强不息。<br>')
        // document.write('            <h3>官方刊物</h3>')
        // document.write('              学会的中央报纸为《红松报》每周一刊<br>')
        // document.write('              学会的中央书刊为《挚友》企划暂未开始<br>')
        // document.write('            <h3>学会宣言</h3>')
        // document.write('              我志愿加入中国红松学会，承认社纲社章，执行学社的决议，遵守学社的纪律，保守学社的秘密，不忘马克思列宁主义和毛泽东思想，不忘阶级斗争，坚决反对中国特色修正共产党，随时准备牺牲个人的一切，为全人类全中国彻底解放奋斗终身！<br>')
        // document.write('        </span>')
        // document.write('    </li>')
        // document.write('    <div class="poster-container">')
        // document.write('        <img src="https://i.328888.xyz/2022/12/17/4mRv5.jpeg" alt="poster1" style="width: 100%;">')
        // document.write('        <p>红松学社宣传海报-001</p>')
        // document.write('    </div>')
        // document.write('</ul>')
        document.write('    <ul class="link-box">')
        document.write('        <br>')
        document.write('        <li>')
        document.write('            <h1 style="text-align: center;">本页面仍在开发中</h1><br>')
        document.write('            <h1 style="text-align: center;">This Page is still under development</h1><br>')
        document.write('            <h1 style="text-align: center;">Diese Seite befindet sich noch in der Entwicklung</h1><br>')
        document.write('            <h1 style="text-align: center;">Cette page est en cours de développement</h1><br>')
        document.write('            <h1 style="text-align: center;">Эта страница находится в стадии разработки</h1><br>')
        document.write('            <h1 style="text-align: center;">このページは現在も開発中です</h1><br>')
        document.write('            <h4 style="text-align: center;">——By ArbeiterKlassen</h4><br>')
        document.write('        </li>')
        document.write('    </ul>')
    }
    if(page==3){
        document.write('<ul class="link-box">')
        document.write('    <br>')
        document.write('    <li class="person-img-li" style="text-align: center;">')
        document.write('        <img src="../img/club/4.jpg" alt="Marxist Society" id="person-img" style="width: 37%;">')
        document.write('    </li>')
        document.write('    <li>')
        document.write('        <h3 style="text-align: center;">呼和浩特马克思主义学会</h3>')
        document.write('        <h5 style="text-align: center;">Marxist Society, Huhhot</h5>')
        document.write('        <span class="description" style="width: 100%;">')
        document.write('            <h3>社长：</h3>塔特林<br>QQ：2876298815 <br>')
        document.write('            <h3>成立日期：2021.8.3</h3>')
        document.write('            <h3>介绍</h3>')
        document.write('              呼和浩特马克思主义学社（简称呼马），是呼和浩特地区及周边左翼学生联盟，是主要面向学生群体的进步群众组织，学会的最高理想是实现共产主义。本社以共产主义为主要思想，以马克思主义、列宁主义、毛泽东主义为指导思想的理论基础。积极开展对马克思主义理论的学习，积极开展马克思主义理论的宣传与实践活动，帮助同学们用所学理论知识解决在理论学习、生活实践中所遇到的难点和疑点问题，在实践中培养并造就青年一代的马克思主义者。<br>')
        document.write('           <h3>活动范围：</h3>')
        document.write('              本学会活动范围以呼和浩特市及其行政范围内的周边旗县为主，主要活跃于各大高中，目前已在呼市二中，呼市十八中、呼市一中内组建下属分会，在铁一中，十四中，十六中，二十九中，回中，北四，察素齐中学皆有同志分部。<br>')
        document.write('            <h3>意识形态：</h3>')
        document.write('              本学会以共产主义为主要思想，以马克思主义、列宁主义、毛泽东主义为指导思想的理论基础，同时承认并团结大部分左翼，我们主张在容忍政治倾向差异内，以团结大多数支持共产主义事业的青年学生为基础，以和谐互助，和平共处，求同存异，互相尊重为方针，开展共产主义等左翼理论和实践教学。<br>')
        document.write('            <h3>活动时间：</h3>')
        document.write('              各大分会内部自主安排，全市活动时间灵活安排。')
        document.write('        </span>')
        document.write('    </li>')
        document.write('    <br>')
        document.write('    <li>')
        document.write('        <p style="text-align:center ;"><strong>“世界是你们的，也是我们的，但是归根结底是你们的。你们青年人朝气蓬勃，正在兴旺时期，好像早晨八九点钟的太阳。希望寄托在你们身上。”</strong><h6 style="text-align: right;">——毛泽东</h6></p>')
        document.write('        <p style="text-align:center ;"><strong>“坚信生活的美好，保持乐观的态度，要知道革命总是无往不胜的。”</strong><h6 style="text-align: right;">——瓦列里·萨布林</h6></p>')
        document.write('    </li>')
        document.write('</ul>')
    }
    if(page==4){
        document.write('<ul class="link-box">')
        document.write('    <br>')
        document.write('    <li class="person-img-li" style="text-align: center;">')
        document.write('        <img src="../img/club/5.jpg" alt="Northbridge Marxist Union" id="person-img" style="width: 37%;">')
        document.write('    </li>')
        document.write('    <li>')
        document.write('        <h3 style="text-align: center;">北桥马克思主义联合社</h3>')
        document.write('        <h5 style="text-align: center;">Northbridge Marxist Union</h5>')
        document.write('        <span class="description" style="width: 100%;">')
        document.write('            <h3>社长：</h3>咲不出来<br>QQ：2876298815 <br>')
        document.write('            <h3>成立日期：2023.1.9</h3>')
        document.write('            <h3>介绍</h3>')
        document.write('              北桥马克思主义联合社（简称北桥联社），是包头市地区及周边的左翼学生社团，是主要面向包头市广大学生群体的组织。本联合社以实现共产主义为最高纲领，以马克思列宁主义，毛泽东思想为指导思想，积极开展读书会，定期举办周刊等马克思主义相关活动来实现对马克思主义理论的学习与实践，引导并培养新一代马克思主义者。<br>')
        document.write('           <h3>活动范围：</h3>')
        document.write('              目前本联合社活动范围为包头市及其周边，主要活动于本地各大高中，目前在包六中，包铁五中，包九中，包头市机电工业职业学院有同志分布<br>')
        document.write('            <h3>意识形态：</h3>')
        document.write('              本联合社以马克思主义，列宁主义，毛泽东思想为指导思想，同时承认并团结大部分泛左翼群体。我们将在有限的意识形态差异内，以团结大部分先进思想的学生阶层为根基，以求同存异和谐互助为准则，开展无限的共产主义活动。<br>')
        document.write('            <h3>活动时间：</h3>')
        document.write('              无具体时间，灵活安排。')
        document.write('        </span>')
        document.write('    </li>')
        document.write('    <br>')
        document.write('    <li>')
        document.write('        <p style="text-align:center ;"><strong>“如果我们选择了最能为人类而工作的职业，那么，重担就不能把我们压倒，因为这是为大家作出的牺牲；那时我们所享受的就不是可怜的、有限的、自私的乐趣，我们的幸福将属于千百万人，我们的事业将悄然无声地存在下去，但是它会永远发挥作用，而面对我们的骨灰，高尚的人们将洒下热泪。”</strong><h6 style="text-align: right;">——卡尔·马克思</h6</p>')
        document.write('    </li>')
        document.write('</ul>')
    }
    if(page==5){
        document.write('<ul class="link-box">')
        document.write('    <br>')
        document.write('    <li class="person-img-li" style="text-align: center;">')
        document.write('        <img src="../img/club/6.jpg" alt="Northbridge Marxist Union" id="person-img" style="width: 37%;">')
        document.write('    </li>')
        document.write('    <li>')
        document.write('        <h3 style="text-align: center;">海拉尔二中马列社-为公社</h3>')
        document.write('        <span class="description" style="width: 100%;">')
        document.write('            <h3>社长：</h3>杨哲 QQ：2038986848 <br>')
        document.write('            <h3>为公社书记：</h3>赵倚力奇<br>')
        document.write('            <h3>成立日期：2021.5.1</h3>')
        document.write('            <h3>介绍</h3>')
        document.write('              海拉尔第二中学马列社/为公社，是面向海二中学生的学生社团。为海二中具有进步思想的左翼学生提供理论学习和社会实践活动，为培养坚定的马克思主义者和进步学生而奋斗。<br>')
        document.write('            <h3>社团发展史</h3>')
        document.write('              海二中马列社/为公社创建于2021年五月，杨哲为现任马列社社长，赵倚力奇为现任为公社书记。<br>')
        document.write('            <h3>组织架构：</h3>')
        document.write('              为公社是马列社的外围社团，社员需在为公社经过考核方可进入马列社<br>')
        document.write('            <h3>开展活动：</h3>')
        document.write('              社团目前出版报纸，向群众介绍，宣传马列思想和理论。开展读书会和理论研讨，并且不定期开展社会调查实践活动。<br>')
        document.write('           <h3>活动范围：</h3>')
        document.write('              主要在海二中校内<br>')
        document.write('           <h3>社员组成：</h3>')
        document.write('              海二中学生<br>')
        document.write('            <h3>目标远景：</h3>')
        document.write('              本社以马克思列宁主义，毛泽东思想为指导思想，向广大群众宣传马克思主义理论，意在培养一批坚定的马克思主义学生，提高广大学生的思政素质，理论素养，从而坚定共产主义必胜的信念，成为社会主义合格接班人。<br>')
        document.write('            <h3>加入我们：</h3>')
        document.write('              如果你对马列主义，共运史以及其他左翼理论有兴趣，有为广大无产者求解放的信念和对共产主义必然胜利的信心，请加入我们。我们是工农的孩子，也必然会是社会的主人。。')
        document.write('        </span>')
        document.write('    </li>')
        document.write('    <br>')
        document.write('    <li>')
        document.write('        <p style="text-align:center ;"><strong>“让我们忠于理想，让我们面对现实”</strong><h6 style="text-align: right;">———切 格瓦拉</h6</p>')
        document.write('    </li>')
        document.write('</ul>')
    }
    if(page==6){
        document.write('    <ul class="link-box">')
        document.write('        <br>')
        document.write('        <li>')
        document.write('            <h1 style="text-align: center;">本页面仍在开发中</h1><br>')
        document.write('            <h1 style="text-align: center;">This Page is still under development</h1><br>')
        document.write('            <h1 style="text-align: center;">Diese Seite befindet sich noch in der Entwicklung</h1><br>')
        document.write('            <h1 style="text-align: center;">Cette page est en cours de développement</h1><br>')
        document.write('            <h1 style="text-align: center;">Эта страница находится в стадии разработки</h1><br>')
        document.write('            <h1 style="text-align: center;">このページは現在も開発中です</h1><br>')
        document.write('            <h4 style="text-align: center;">——By ArbeiterKlassen</h4><br>')
        document.write('        </li>')
        document.write('    </ul>')
    }
    if(page==7){
        document.write('    <ul class="link-box">')
        document.write('        <br>')
        document.write('        <li>')
        document.write('            <h1 style="text-align: center;">本页面仍在开发中</h1><br>')
        document.write('            <h1 style="text-align: center;">This Page is still under development</h1><br>')
        document.write('            <h1 style="text-align: center;">Diese Seite befindet sich noch in der Entwicklung</h1><br>')
        document.write('            <h1 style="text-align: center;">Cette page est en cours de développement</h1><br>')
        document.write('            <h1 style="text-align: center;">Эта страница находится в стадии разработки</h1><br>')
        document.write('            <h1 style="text-align: center;">このページは現在も開発中です</h1><br>')
        document.write('            <h4 style="text-align: center;">——By ArbeiterKlassen</h4><br>')
        document.write('        </li>')
        document.write('    </ul>')
    }
}
