document.write(' <div class="sign-container">')
document.write('     <ul class="column_box" id="like-box">')
document.write('         <li class="column-title">')
document.write('             <span class="at-sort b-b-ece fl"><a class="at-sort-comment-a c-666 fl">Former</a></span>')
document.write('         </li>')


document.write('         <li class="person-intro-detail gradient-text">')
document.write('             <h2>2022-12-4</h2>')
document.write('         </li>')
document.write('         <li class="person-intro-detail">')
document.write('             <h3>久违的更新了公告啊（笑）<br></h3>')
document.write('             <h3>开发了新的评论区功能-涵盖文章-宣传栏-评论区 三位一体<br></h3>')
document.write('             <h3>继续推进网站代码的公用化（有新的建议也可以copy我在GitHub上的代码研究或者提交issue）（<br></h3>')
document.write('             <h3>两个月以来发生了很多事<br></h3>')
document.write('             <h3>内蒙古左联AULIM成立了，新的网课计划也在逐步进行<br></h3>')
document.write('             <h3>我们也认识了很多新的同志<br></h3>')
document.write('             <h3>然而疫情还是没什么好的进展<br></h3>')
document.write('             <br>')
document.write('             <h3>唉<br></h3>')
document.write('             <h3>技术修复：<br></h3>')
document.write('             <h3>···计划开发分页功能并优化界面<br></h3>')
document.write('             <h3>···移除了PC端的首页头图展示（但代码没有被删除）（<br></h3>')
document.write('             <h3>功能扩展：<br></h3>')
document.write('             <h3>···评论区和宣传栏的建立<br></h3>')
document.write('             <h3>···还有什么呢。。<br></h3>')
document.write('         </li>')


document.write('         <li class="person-intro-detail gradient-text">')
document.write('             <h2>2022-10-5</h2>')
document.write('         </li>')
document.write('         <li class="person-intro-detail">')
document.write('             <h3>增加里站界面<br></h3>')
document.write('             <h3>文件归档增加支持多关键词的搜索功能<br></h3>')
document.write('             <h3>访问方式：<a href="https://www.wgsoc.top/templates/inside.index.html">https://www.wgsoc.top/templates/inside.index.html</a><br></h3>')
document.write('             <h3>或<a href="https://inside.wgsoc.top">inside.wgsoc.top</a><br></h3>')
document.write('             <h3>当然可以从首页某个位置进入里站（<br></h3>')
document.write('             <h3>赤原社官方公众号也在开发中！<br></h3>')
document.write('             <h3>技术修复：<br></h3>')
document.write('             <h3>···迁移了一些危险性拉满的文章<br></h3>')
document.write('             <h3>···增加里站头图（<br></h3>')
document.write('             <h3>功能扩展：<br></h3>')
document.write('             <h3>···文件归档增加支持多关键词的搜索功能<br></h3>')
document.write('             <h3>···修改文件归档<br></h3>')
document.write('             <h3>乐<br></h3>')
document.write('         </li>')


document.write('         <li class="person-intro-detail gradient-text">')
document.write('             <h2>2022-9-26</h2>')
document.write('         </li>')
document.write('         <li class="person-intro-detail">')
document.write('             <h3>赤原社开业大成功！<br></h3>')
document.write('             <h3>技术修复：<br></h3>')
document.write('             <h3>···代码公用化完成，现在开发简单多了<br></h3>')
document.write('             <h3>···增加头图，美化网站页面，防止颈椎病（<br></h3>')
document.write('             <h3>功能扩展：<br></h3>')
document.write('             <h3>···增加文件归档，更新友链页面，移除了一些老旧内容<br></h3>')
document.write('             <h3>···社团官网页面现在是中英双语的辣!!！<br></h3>')
document.write('             <h3>···It is English-Chinese Introduction!!！<br></h3>')
document.write('             <h3>乐<br></h3>')
document.write('         </li>')


document.write('         <li class="person-intro-detail gradient-text">')
document.write('             <h2>2022-2-2</h2>')
document.write('         </li>')
document.write('         <li class="person-intro-detail">')
document.write('             <h3>修复BUG：文章底部的小电视图标不显示<br></h3>')
document.write('             <h3>发现BUG：目前在ipad端chrome内核浏览器上存在sign时间不显示的问题<br></h3>')
document.write('             <h3>@包头九中赤原青年马克思主义社 的宣传页面开发完成<br></h3>')
document.write('             <h3>之后考虑将@包头市田家炳中学马列红星社 宣传页面添加到友情链接<br></h3>')
document.write('         </li>')


document.write('         <li class="person-intro-detail gradient-text">')
document.write('             <h2>2022-1-24</h2>')
document.write('         </li>')
document.write('         <li class="person-intro-detail">')
document.write('             <h3>技术改进：实现页面头尾部的JS化，现在开发新页面效率提升了<br></h3>')
document.write('             <h3>@ArbeiterKlassen 的个人博客已合并为本站的子域名到：<br></h3>')
document.write('             <span id="description"><a href="https://self.wgsoc.top">https://self.wgsoc.top</a></span><br>')
document.write('             <h3>仍可以使用:</h3>')
document.write('             <span id="description"><a href="https://arbeiterklassen.github.io/self">https://arbeiterklassen.github.io/self</a></span><br>')
document.write('             <br>')
document.write('             <h3>@包头九中赤原青年马克思主义社 的宣传页面正在开发中<br></h3>')
document.write('             <h3>增加望关社论站的Bili宣传账号（在底部小电视图标访问）<br></h3>')
document.write('         </li>')
document.write('         <br>')


document.write('         <li class="person-intro-detail gradient-text">')
document.write('             <h2>2022-1-22</h2>')
document.write('         </li>')
document.write('         <li class="person-intro-detail">')
document.write('             <h3>本站将改组成为@包头九中赤原青年马克思主义社 的社团专站<br></h3>')
document.write('             <h3>原有功能不变，现应包括：<br></h3>')
document.write('             <span id="description">1. ArbeiterKlassen 和社团成员文章的记录工作</span><br>')
document.write('             <span id="description">2. 马克思主义的宣传工作</span><br>')
document.write('             <span id="description">3. 全国各界有意加入这个企划的同志，并已来稿文章的文章记录，发布和宣传工作</span><br>')
document.write('             <br>')
document.write('             <h3>ArbeiterKlassen将长期作为网站的运维<br></h3>')
document.write('             <h3>望关 wgsoc.top 将增加对@包头九中赤原青年马克思主义社 的宣传功能<br></h3>')
document.write('         </li>')
document.write('         <br>')


document.write('         <li class="person-intro-detail gradient-text">')
document.write('             <h2>2022-1-21</h2>')
document.write('         </li>')
document.write('         <li class="person-intro-detail">')
document.write('             <h3>ArbeiterKlassen放假了，于是决定进行网站的再运营<br></h3>')
document.write('             <h3>本网站已更名为望关，取自“雄关漫道真如铁，而今迈步从头越”<br></h3>')
document.write('             <h3>当前网站的访问方式：<br></h3>')
document.write('             <span id="description">1. https://www.wgsoc.top (推荐)</span><br>')
document.write('             <span id="description">2. https://arbeiterklassen.github.io/Social (备用)</span><br>')
document.write('             <h3>考虑到CDS的纲领问题，暂时将CDS在首页的信息移除，仅保留友链的QR码<br></h3>')
document.write('             <h3>目前存在的主要问题是：<br>1.网站宣传不出去，<br>2.网站没钱租服务器所以只能搭在Github上(已绑定域名)<br>3.网站人少没有内容，我文笔也渣<br>4.没时间管理网站<br>5.最重要的一点，晶哥</h3>')
document.write('         </li>')
document.write('         <br>')


document.write('         <li class="person-intro-detail gradient-text">')
document.write('             <h1>2021-8-10</h1>')
document.write('         </li>')
document.write('         <li class="person-intro-detail">')
document.write('             <h3>这里是ArbeiterKlassen&Comerades的社论站<br></h3>')
document.write('             <h3>虽然很烂，但是内容也是我们亲自写出来的<br></h3>')
document.write('             <h3>目前的我和@Faschiung是该项目的主要参与者<br></h3>')
document.write('             <h3>全世界无产者，联合起来！<br>')
document.write('                 Proletarier aller Länder, vereinigt euch!<br>')
document.write('                 人民万岁！<br>')
document.write('                 Vive le peuple!<br>')
document.write('             </h3>')
document.write('         </li>')


document.write('     </ul>')
document.write(' </div>')