document.write('    <footer class="footer">')
document.write('        <div class="footer-line">Powered By <a href="https://github.com/arbeiterklassen/Social" target="_blank">WangGuan Sociology</a> 浙ICP备1145141919810号• © 2023</div>')
document.write('    </footer>')
document.write('    <script type="text/javascript" src="../js/jquery-3.4.1.min.js"></script>')
document.write('    <script type="text/javascript" src="../js/sweetalert.min.js"></script>')
document.write('    <script type="text/javascript" src="../js/pace.min.js"></script>')
document.write('    <script type="text/javascript" src="../js/base.js"></script>')
document.write('    <script type="text/javascript" src="../js/d-audio.js"></script>')
document.write('    <script type="text/javascript" src="../js/myPagination.js"></script>')